All files
Abraham-Chileshe/myweatherapp pull request #1
Opened 2024-01-29 04:39 UTC by Abraham-Chileshe

All files to the app

2024-01-29 09:51 UTC, Hostridet requested changes
уже 3 раз вижу этот код, удачи с правками

2024-01-29 09:51 UTC, Hostridet commented on lib/main.dart
> +  void search() async {
Получение данных - не логика экрана, вынести в репозиторий

2024-01-29 09:51 UTC, Hostridet commented on lib/main.dart
> +    final response = await dataService.getWeather(cityTextController.text, context);
С бэка придет ошибка, тогда поймем критику
Сделать обработку ошибок в `FutureBuilder`

2024-01-29 09:51 UTC, Hostridet commented on lib/main.dart
> +                if (_response != null)
убрать, _response должен получаться в `FutureBuilder`, где можно будет обработать состояние `onLoad` и _response никогад не будет null

2024-01-29 09:51 UTC, Hostridet commented on lib/models.dart
> +  WeatherInfo({required this.description, required this.icon});
const

2024-01-29 09:51 UTC, Hostridet commented on lib/models.dart
> +  TemperatureInfo({required this.temperature});
const

2024-01-29 09:51 UTC, Hostridet commented on lib/service.dart
> +  Future<WeatherResponse> getWeather(String city, BuildContext context) async {
Сервис не должен знать о contextе, контекст может измениться, а сервис будет иметь устаревший контекст. Передавать язык сразу

2024-01-29 09:51 UTC, Hostridet commented on lib/service.dart
> +    final response = await http.get(uri);
зпрос в `try {} catch {}` и прокинут ьисключение

2024-01-29 09:51 UTC, Hostridet commented on lib/main.dart
> +            alignment: const Alignment(-0.9, 0.9),
Две кнопки для туггла, может одну сделать? on/off

2024-01-29 12:53 UTC, Abraham-Chileshe commented on lib/main.dart
> +            alignment: const Alignment(-0.9, 0.9),
я добавил одну кнопку, которая переключается между языками

2024-01-29 13:01 UTC, Abraham-Chileshe commented on lib/service.dart
> +    final response = await http.get(uri);
Я тоже сделал это

2024-01-29 13:12 UTC, Abraham-Chileshe commented on lib/models.dart
> +  TemperatureInfo({required this.temperature});
Почему "const"? потому что я думаю, что использование const неприменимо для большинства частей классов, потому что значения определяются во время выполнения на основе анализируемых данных JSON.

2024-01-29 13:24 UTC, Abraham-Chileshe commented on lib/main.dart
> +                if (_response != null)
Я переписал код так, чтобы он использовал Future Builder для обработки асинхронной выборки данных о погоде. Статус загрузки отображается с помощью кругового индикатора выполнения, а результат отображается, когда данные доступны.

2024-01-29 14:09 UTC, Abraham-Chileshe commented on lib/main.dart
> +    final response = await dataService.getWeather(cityTextController.text, context);
исправлено

2024-01-29 14:17 UTC, Hostridet commented on lib/models.dart
> +  TemperatureInfo({required this.temperature});
Под константы выделяется статическая память при компиляции, что позволяет сэкономить память в рантайме при создании константного объекта

2024-01-29 14:18 UTC, Hostridet commented on lib/service.dart
> +  Future<WeatherResponse> getWeather(String city, BuildContext context) async {
Пропустил грубейшую ошибку, необходимо исправить

2024-01-30 08:06 UTC, Abraham-Chileshe commented on lib/service.dart
> +  Future<WeatherResponse> getWeather(String city, BuildContext context) async {
я пытался их починить. я не знаю, это ли вы имели в виду

2024-01-30 08:12 UTC, Abraham-Chileshe commented on lib/models.dart
> +  WeatherInfo({required this.description, required this.icon});
Я попытался изменить final на contest и получил множество досадных ошибок. Я провел небольшое исследование, и вот что я нашел

" использование const больше связано с константами времени компиляции, и если значения неизвестны во время компиляции, вам не следует использовать const. Если вам все еще нужны экземпляры этих классов, рассмотрите возможность использования final вместо этого"

поэтому я думаю, что final подходит в данном случае, потому что значения weather неизвестны во время компиляции, только во время выполнения

2024-01-30 08:12 UTC, Abraham-Chileshe commented on lib/models.dart
> +  TemperatureInfo({required this.temperature});
Я попытался изменить final на contest и получил множество досадных ошибок. Я провел небольшое исследование, и вот что я нашел

" использование const больше связано с константами времени компиляции, и если значения неизвестны во время компиляции, вам не следует использовать const. Если вам все еще нужны экземпляры этих классов, рассмотрите возможность использования final вместо этого"

поэтому я думаю, что final подходит в данном случае, потому что значения weather неизвестны во время компиляции, только во время выполнения

2024-01-31 10:07 UTC, Hostridet commented on lib/models.dart
> +  WeatherInfo({required this.description, required this.icon});
Конструктор, не переменная

2024-02-01 03:02 UTC, merged